name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install software
      run: sudo apt-get install valgrind lcov

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_dir -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build_dir --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build_dir
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: MemCheck
      working-directory: ${{github.workspace}}/build_dir
      run: ctest -T memcheck

    - name: Coverage
      working-directory: ${{github.workspace}}/build_dir
      run: |
        rm -rf *
        cmake -DCMAKE_BUILD_TYPE=Coverage ..
        cmake --build . --config Coverage
        ctest -C Test
        ctest -T coverage
        lcov --directory . --capture --output-file coverage.info --base-directory .
        bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
